In [7]:
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# To check for dimensions
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat)
print(mat.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
mat2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(mat2)
print(mat2.shape)

print(mat2.reshape(5, 2)) # Reshapes the current array from 2 rows and 5 colums to 5 rows and 2 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Identity matrix
np.eye(5) # Creates an identity matrix of 5x5 dimensions

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Array: {arr}')
print(f'Shape: {arr.shape}')
print(f'Number of dimensions: {arr.ndim}')
print(f'Size(total number of elements): {arr.size}')
print(f'Data Type: {arr.dtype}')
print(f'Item size(in bytes): {arr.itemsize}')

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Size(total number of elements): 9
Data Type: int64
Item size(in bytes): 8


In [39]:
# Vector Operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Element wise addition
print(f'Addition: {arr1+arr2}')
print(f'Subtraction: {arr1-arr2}')
print(f'Multiplication: {arr1*arr2}')
print(f'Division: {arr1/arr2}')
print(f'Double division: {arr1//arr2}')


Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Double division: [0 0 0 0 0]


In [ ]:
# Universal Functions
arr = np.array([10, 20, 30])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[3.16227766 4.47213595 5.47722558]
[2.20264658e+04 4.85165195e+08 1.06864746e+13]
[-0.54402111  0.91294525 -0.98803162]
[2.30258509 2.99573227 3.40119738]


In [46]:
# Array Slicing and Indexing
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f'Array:\n {mat}')

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [68]:
# Accessing a single element
print(mat[0][0])

# Accessing a bunch of elements
print(mat[1:, 2:])
print()
# Selecting 3, 4, 7, 8
print(mat[0:2, 2:])

1
[[ 7  8]
 [11 12]]

[[3 4]
 [7 8]]


In [67]:
# Selecting 6, 7, 10, 11
print(mat[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [69]:
# Modifying elements
mat[0, 2] = 199
print(mat)

[[  1   2 199   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [70]:
mat[2:] = 99
print(mat)

[[  1   2 199   4]
 [  5   6   7   8]
 [ 99  99  99  99]]


In [ ]:
# Statistical Concepts :- Normalization

# To have a mean of 0 and std of 1
data = np.array([1,2,3,4,5])

# Calculate mean and std
mean = np.mean(data)
std_dev = np.std(data)

print(f'Mean: {mean}')
print(f'Standard Deviation: {std_dev}')

# Normalizing
normalized_data = (data - mean)/std_dev
print(f'Normalized Data: {normalized_data}')


Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [79]:
# median, variance
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 9])

median = np.median(data)
print(f'Median: {median}')

variance = np.var(data)
print(f'Variance: {variance}')

Median: 5.5
Variance: 9.6875


In [89]:
# Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(data > 5)
print(data % 2 == 0)

print(data[data > 5])
print(data[data%2 == 0])
print(data[data%2 != 0])

print(data[(data>5) & (data<=8)])
print(data[(data < 2) | (data>8)])

[False False False False False  True  True  True  True  True]
[False  True False  True False  True False  True False  True]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
[1 3 5 7 9]
[6 7 8]
[ 1  9 10]
